### ISSUE TITLE
Global Enhancement Post

### ISSUE THREAD

**Issue by Dyl-M** [Dyl-M/youtube_release_tracker#3]
## TODO-List

- [ ] Reporting workflow: automation for playlists reports (weekly, monthly and yearly).
- [ ] Create a better way to commit logs to the main branch.

## Contribution

This issue is designed to evolve / to not be closed (until the project dies), to list enhancement that can be made, like an unrestricted roadmap.

If you want to collaborate on this repository, check the TODO-List, create a issue related to one of a listed feature, create your solution and submit your pull request. This issue will be updated in consequence.

New features and code issues have to be written / reported by creating a **New Issue**.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.
